#define FLOW_TAP_TERM 50
#define CHORDAL_HOLD
#undef DEBOUNCE
#define DEBOUNCE 5

#undef TAPPING_TERM
#define TAPPING_TERM 300

#define ONESHOT_TAP_TOGGLE 2

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "rAboj/pj70bX"
#define LAYER_STATE_16BIT

#define TAPPING_TERM_PER_KEY
