#define FLOW_TAP_TERM 167
#define CHORDAL_HOLD
#undef DEBOUNCE
#define DEBOUNCE 5

#undef TAPPING_TERM
#define TAPPING_TERM 300

#define ONESHOT_TAP_TOGGLE 2

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define HOLD_ON_OTHER_KEY_PRESS
#define SERIAL_NUMBER "emrpr/JaPWAp"
#define LAYER_STATE_16BIT

#define TAPPING_TERM_PER_KEY








/* Custom QMK Features */
#define LEADER_TIMEOUT 300
#define LEADER_PER_KEY_TIMING
//#define LEADER_NO_TIMEOUT