#define FLOW_TAP_TERM 167
#define CHORDAL_HOLD
#undef DEBOUNCE
#define DEBOUNCE 5

#undef TAPPING_TERM
#define TAPPING_TERM 350

#define ONESHOT_TAP_TOGGLE 2

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "emrpr/wOxK3J"
#define LAYER_STATE_16BIT

#define TAPPING_TERM_PER_KEY








/* Custom QMK Features */
#define LEADER_TIMEOUT 300
#define LEADER_PER_KEY_TIMING
#define LEADER_NO_TIMEOUT