manifest:
  remotes:
    - name: slicemk
      url-base: https://github.com/xudongzheng/
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: slicemk
      revision: v20250729-rgb
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: main
    - name: zmk-leader-key
      remote: urob
      revision: main
  self:
    path: config